default: &default
  adapter: mysql2
  pool: 5
  host: localhost
  username: root
  password: root

development:
  <<: *default
  database: db/api_interview_development

test:
  <<: *default
  database: db/api_interview_test

production:
  <<: *default
  database: db/api_interview_production
